stages:
  - test
  - build

variables:
  CI_IMAGE:                        "docker.io/paritytech/ci-unified:latest"
  BUILDAH_IMAGE:                   "quay.io/buildah/stable:v1.29"
  BUILDAH_COMMAND:                 "buildah --storage-driver overlay2"
  VAULT_ADDR:                      "https://vault.parity-mgmt-vault.parity.io"
  VAULT_AUTH_PATH:                 "gitlab-parity-io-jwt"
  VAULT_AUTH_ROLE:                 "gitlab_${CI_PROJECT_NAME}"
  HELM_SECRETS_DRIVER:             vals

default:
  image: $CI_IMAGE
  tags:
    - linux-docker-vm-c2 

test-unit:
  stage:                           test
  rules:
    - if: $CI_COMMIT_REF_NAME == "oleg/bazel_test"
  script:
    - echo "Test..."
build:
  stage:                           build
  rules:
    - if: $CI_COMMIT_REF_NAME == "oleg/bazel_test"
  script:
    - bazel build //cli --action_env=PATH=$PATH --remote_cache=https://storage.googleapis.com/bazel-cache-parity-build-stg --google_default_credentials
